all: headself longcmd1 longcmd2 showargs showpath

.PHONY: clean
clean:
	rm -f headself longcmd1 longcmd2 showargs showpath

headself: headself.c
longcmd1: longcmd1.c
longcmd2: longcmd2.c
showargs: showargs.c
showpath: showpath.c
